import * as THREE from 'three';
import {GameState} from './GameState';import {Input} from '../input/Input';import {createPhysicsWorld,type PhysicsWorldHandle} from '../physics/PhysicsWorld';import {ThirdPersonCamera} from '../camera/ThirdPersonCamera';import {ThirdPersonController} from '../character/ThirdPersonController';import {TestWorld} from '../world/TestWorld';import {PhaserOverlay} from '../ui/PhaserOverlay';
export class Game{
 readonly state=new GameState();readonly scene=new THREE.Scene();readonly camera=new THREE.PerspectiveCamera(55,innerWidth/innerHeight,.05,250);readonly renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:'high-performance'});readonly input:Input;readonly orbit:ThirdPersonCamera;readonly world!:TestWorld;readonly player!:ThirdPersonController;readonly physicsPromise:Promise<PhysicsWorldHandle>;readonly overlay:PhaserOverlay;
 private physics!:PhysicsWorldHandle;private last=performance.now();private acc=0;private frames=0;private running=false;private resizeObserver:ResizeObserver|null=null;
 constructor(private readonly root:HTMLElement){this.renderer.setPixelRatio(Math.min(devicePixelRatio,2));this.renderer.setSize(innerWidth,innerHeight);this.renderer.shadowMap.enabled=true;this.renderer.shadowMap.type=THREE.PCFSoftShadowMap;this.renderer.outputColorSpace=THREE.SRGBColorSpace;root.appendChild(this.renderer.domElement);this.input=new Input(this.renderer.domElement);this.orbit=new ThirdPersonCamera(this.camera);this.overlay=new PhaserOverlay(this.state);this.scene.background=new THREE.Color(0x8ea4bd);this.scene.fog=new THREE.Fog(0x8ea4bd,30,115);this.physicsPromise=this.initialize();this.resizeObserver=new ResizeObserver(()=>this.resize());this.resizeObserver.observe(root);addEventListener('wheel',e=>this.orbit.zoom(e.deltaY*.003),{passive:true});}
 async initialize(){this.physics=await createPhysicsWorld();this.world=new TestWorld(this.physics);this.scene.add(this.world.group);this.player=new ThirdPersonController(this.physics,this.input,this.orbit,this.state);this.scene.add(this.player.object);this.orbit.update(1,this.player.object);return this.physics;}
 start(){if(this.running)return;this.running=true;requestAnimationFrame(t=>this.loop(t));}
 private loop(now:number){if(!this.running)return;const dt=Math.min((now-this.last)/1000,.033);this.last=now;this.input.update();if(this.input.consumeMenu()){this.state.paused=!this.state.paused;const menu=document.getElementById('menu-panel');if(menu)menu.hidden=!this.state.paused;}if(this.input.consumeReset())this.state.reset();if(!this.state.paused&&this.player){if(this.state.consumeReset())this.player.reset();this.player.update(dt);this.physics.step();this.orbit.lookDelta(this.input.look.x*22,this.input.look.y*22);this.orbit.update(dt,this.player.object);}this.renderer.render(this.scene,this.camera);this.hud(dt);requestAnimationFrame(t=>this.loop(t));}
 private hud(dt:number){this.acc+=dt;this.frames++;if(this.acc>=.5){this.state.fps=Math.round(this.frames/this.acc);this.acc=0;this.frames=0;}const a=document.getElementById('state-value'),b=document.getElementById('speed-value'),c=document.getElementById('fps-value');if(a)a.textContent=this.state.playerState;if(b)b.textContent=`${this.state.speed.toFixed(1)} m/s`;if(c)c.textContent=String(this.state.fps);}
 private resize(){const w=this.root.clientWidth||innerWidth,h=this.root.clientHeight||innerHeight;this.camera.aspect=w/h;this.camera.updateProjectionMatrix();this.renderer.setSize(w,h,false);}
 dispose(){this.running=false;this.resizeObserver?.disconnect();this.overlay.destroy();this.player?.dispose();this.renderer.dispose();this.root.replaceChildren();}
}